version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PGHOST=${PGHOST}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGPORT=${PGPORT} 
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD_DOCKER}
      - POSTGRES_DB=${PGDATABASE_DOCKER}
    ports:
      - "5432:5432"
